### ISSUE TITLE
Mapping modification help 

### ISSUE THREAD

**Issue by MusicMan74** [sfzinstruments/WilkinsonAudio.NakedDrums#1]
Can someone kindly explain how to modify the mapping text files such that Snare "1" can be played by BOTH midi notes 38 and 40?

I am fairly well versed in the 'SFZ' file format (groups, regions, etc.) but don't quite follow the TXT file format here with 'define' variable substitutions...

If 'macro.txt' is modified such that 

$KEY_SNR1 38
becomes
$KEY_SNR1 40

then Snare1 only plays on midi note 40.

Is there a workaround?

**Comment by MusicMan74** [comment]
Was able to answer my own question after a little more digging.
IMO these changes make the kit much more playable on a keyboard :)

I'll share my solution here for anyone else looking to make a similar modification:

I. To play "SNR1" on both midi notes 38 and 40:

Modify the 7 "data\group\snare*.txt" files as follows
    1. Comment ("//") all lines after 'key=$KEY_SNR2' 
    2. Copy the 4 lines after 'key=$KEY_SNR1' and paste after the 'key=$KEY_SNR2' line



II. To play the "KICK" drum on both midi notes 35 and 36:

A. Modify "data\keymap.txt", "User\Naked Drums TD-12 keymap.txt" and "User\Naked Drums GM keymap.txt" as follows:
    Replace '#define $KEY_KICK 36' line with two lines:
         
         #define $LKEY_KICK 35
         #define $HKEY_KICK 36


B. Modify the 6 "data\group\kick*.txt" files as follows:
    Replace 'key=$KEY_KICK' line with the following four lines:
         
         lokey=$LKEY_KICK
         hikey=$HKEY_KICK
         pitch_keycenter=$HKEY_KICK
         pitch_keytrack=0

**Comment by kinwie** [comment]
Hi, just saw this closed issue. its a good workaround!
I just add an information, when using `pitch_keytrack=0`, then you no more need to put `pitch_keycenter=N`.
Just a bit cleaner :)
